global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['192.168.31.102:8000']  # For Mac/Windows
        # Use 'your-local-ip:8000' on Linux

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']